// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MeritoQuiz.Backend.Data;

#nullable disable

namespace MeritoQuiz.Backend.Migrations
{
    [DbContext(typeof(MeritoQuizDbContext))]
    partial class MeritoQuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MeritoQuiz.Backend.Entities.Category", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid");

                b.Property<string>("Icon")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<string>(("Name"))
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.HasKey("Id");

                b.ToTable("Categories");
            });

            modelBuilder.Entity("MeritoQuiz.Backend.Entities.Question", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid");

                b.Property<Guid>("CategoryId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("ModifiedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasMaxLength(72)
                    .HasColumnType("character varying(72)");

                b.HasKey("Id");

                b.HasIndex("CategoryId");

                b.ToTable("Questions");
            });

            modelBuilder.Entity("MeritoQuiz.Backend.Entities.Answer", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid");

                b.Property<bool>("IsCorrect")
                    .HasColumnType("boolean");

                b.Property<int>("Order")
                    .HasColumnType("integer");

                b.Property<Guid>("QuestionId")
                    .HasColumnType("uuid");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasMaxLength(72)
                    .HasColumnType("character varying(72)");

                b.HasKey("Id");

                b.HasIndex("QuestionId");

                b.ToTable("Answers");
            });

            modelBuilder.Entity("MeritoQuiz.Backend.Entities.Question", b =>
            {
                b.HasOne("MeritoQuiz.Backend.Entities.Category", "Category")
                    .WithMany("Questions")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Category");
            });

            modelBuilder.Entity("MeritoQuiz.Backend.Entities.Answer", b =>
            {
                b.HasOne("MeritoQuiz.Backend.Entities.Question", "Question")
                    .WithMany("Answers")
                    .HasForeignKey("QuestionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Question");
            });

            modelBuilder.Entity("MeritoQuiz.Backend.Entities.Category", b =>
            {
                b.Navigation("Questions");
            });

            modelBuilder.Entity("MeritoQuiz.Backend.Entities.Question", b =>
            {
                b.Navigation("Answers");
            });
#pragma warning restore 612, 618
        }
    }
}
